// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// An account the wallet holds.
class ApiAccount {
  /// The wallet-local identifier.
  final int id;

  /// The height below which this account has no history.
  final int birthday;

  /// Whether the wallet can spend, or only watch.
  final bool canSpend;

  /// The ZIP 32 account index, for accounts derived from a seed.
  final int? hdAccountIndex;

  const ApiAccount({
    required this.id,
    required this.birthday,
    required this.canSpend,
    this.hdAccountIndex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      birthday.hashCode ^
      canSpend.hashCode ^
      hdAccountIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          birthday == other.birthday &&
          canSpend == other.canSpend &&
          hdAccountIndex == other.hdAccountIndex;
}

/// What an account is worth, in zatoshis.
class ApiBalance {
  /// Received, unspent, and settled: what can be sent right now.
  final BigInt spendable;

  /// Received and unspent, but not yet settled.
  final BigInt pending;

  /// Committed by a transaction that has not been mined.
  final BigInt spentUnconfirmed;

  /// Value held on transparent addresses.
  ///
  /// Kept apart from `spendable` because it cannot be sent directly:
  /// transparent funds have to be shielded first.
  final BigInt transparent;

  /// Completeness read in the same database snapshot as the amounts.
  final ApiTransparentCoverage coverage;

  const ApiBalance({
    required this.spendable,
    required this.pending,
    required this.spentUnconfirmed,
    required this.transparent,
    required this.coverage,
  });

  @override
  int get hashCode =>
      spendable.hashCode ^
      pending.hashCode ^
      spentUnconfirmed.hashCode ^
      transparent.hashCode ^
      coverage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBalance &&
          runtimeType == other.runtimeType &&
          spendable == other.spendable &&
          pending == other.pending &&
          spentUnconfirmed == other.spentUnconfirmed &&
          transparent == other.transparent &&
          coverage == other.coverage;
}

/// Why something could not be done.
///
/// Carries the facade's stable numeric code alongside the message. The code is
/// what an application branches on; the message is for a log. Returning only a
/// message — which is what the wallet this replaces does — makes control flow
/// depend on wording, and wording changes.
class ApiError implements FrbException {
  /// The stable code. See `zakura_wallet_facade::ErrorCode`.
  final int code;

  /// What happened, for a human reading a log.
  final String message;

  const ApiError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

/// One transaction, as it affected the wallet.
class ApiHistoryEntry {
  /// The transaction's identifier, in protocol byte order.
  final Uint8List txid;

  /// The height it was mined at, or absent while it is unmined.
  final int? minedHeight;

  /// What the wallet received.
  final BigInt received;

  /// What the wallet spent.
  final BigInt spent;

  /// Whether everything received was change.
  final bool isChangeOnly;

  /// What the wallet received, by where it landed.
  final ApiPoolAmounts receivedByPool;

  /// What the wallet spent, by where it came from.
  final ApiPoolAmounts spentByPool;

  /// Value this transaction paid out to transparent addresses.
  ///
  /// Read from the transaction's own bytes. The wallet's side says only that
  /// value left a pool, not whether it went somewhere public.
  final BigInt paidToTransparent;

  const ApiHistoryEntry({
    required this.txid,
    this.minedHeight,
    required this.received,
    required this.spent,
    required this.isChangeOnly,
    required this.receivedByPool,
    required this.spentByPool,
    required this.paidToTransparent,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      minedHeight.hashCode ^
      received.hashCode ^
      spent.hashCode ^
      isChangeOnly.hashCode ^
      receivedByPool.hashCode ^
      spentByPool.hashCode ^
      paidToTransparent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiHistoryEntry &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          minedHeight == other.minedHeight &&
          received == other.received &&
          spent == other.spent &&
          isChangeOnly == other.isChangeOnly &&
          receivedByPool == other.receivedByPool &&
          spentByPool == other.spentByPool &&
          paidToTransparent == other.paidToTransparent;
}

/// Value, by where in the protocol it sat.
class ApiPoolAmounts {
  /// Value in the Orchard pool.
  final BigInt orchard;

  /// Value in the Ironwood pool.
  final BigInt ironwood;

  /// Value on transparent addresses, which is to say in public.
  final BigInt transparent;

  const ApiPoolAmounts({
    required this.orchard,
    required this.ironwood,
    required this.transparent,
  });

  @override
  int get hashCode =>
      orchard.hashCode ^ ironwood.hashCode ^ transparent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPoolAmounts &&
          runtimeType == other.runtimeType &&
          orchard == other.orchard &&
          ironwood == other.ironwood &&
          transparent == other.transparent;
}

/// What came back from broadcasting.
class ApiSendReceipt {
  /// The transaction's identifier.
  final Uint8List txid;

  /// What the server said. Acceptance means it reached the network, not that
  /// it will be mined.
  final String serverResponse;

  /// Set when the payment was sent but the wallet could not record it.
  ///
  /// Not a failure of the send — the money is gone either way — but the
  /// balance will not account for it until the next scan finds it.
  final String? warning;

  const ApiSendReceipt({
    required this.txid,
    required this.serverResponse,
    this.warning,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ serverResponse.hashCode ^ warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSendReceipt &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          serverResponse == other.serverResponse &&
          warning == other.warning;
}

/// What a payment would cost.
class ApiSpendQuote {
  /// What the recipient receives.
  final BigInt amount;

  /// The fee.
  final BigInt fee;

  /// What comes back to the wallet.
  final BigInt change;

  /// How many notes would be spent, and so how many proofs.
  final int inputs;

  /// Whether this payment leaves the Orchard pool as a ZIP 318 crossing.
  ///
  /// A crossing pays a fixed denomination for a fixed fee, so its numbers are
  /// not negotiable the way an ordinary payment's are.
  final bool crossing;

  const ApiSpendQuote({
    required this.amount,
    required this.fee,
    required this.change,
    required this.inputs,
    required this.crossing,
  });

  @override
  int get hashCode =>
      amount.hashCode ^
      fee.hashCode ^
      change.hashCode ^
      inputs.hashCode ^
      crossing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSpendQuote &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          fee == other.fee &&
          change == other.change &&
          inputs == other.inputs &&
          crossing == other.crossing;
}

/// What the engine is doing.
enum ApiSyncPhase {
  /// Nothing has been scanned yet.
  bootstrapping,

  /// Working backwards through history.
  recovering,

  /// Following the chain tip.
  tracking,

  /// Nothing left to scan right now — which is not the same as finished.
  idle,

  /// Not running.
  stopped,
}

/// How far synchronisation has got.
class ApiSyncProgress {
  /// What the engine is doing.
  final ApiSyncPhase phase;

  /// Commitment coverage between 0 and 1, if there is anything to measure.
  final double? fraction;

  /// The highest block the server reported.
  final int? tip;

  /// The highest block the wallet has scanned.
  final int? scannedTo;

  /// How many blocks remain queued.
  final BigInt blocksRemaining;

  /// Whether the last attempt ended in a failure rather than a finish.
  ///
  /// An unreachable server leaves the engine stopped with nothing queued,
  /// which is what having caught up looks like too. Without this an interface
  /// cannot tell them apart, and would say a wallet is up to date when it has
  /// not spoken to a server.
  final bool failed;

  const ApiSyncProgress({
    required this.phase,
    this.fraction,
    this.tip,
    this.scannedTo,
    required this.blocksRemaining,
    required this.failed,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      fraction.hashCode ^
      tip.hashCode ^
      scannedTo.hashCode ^
      blocksRemaining.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSyncProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          fraction == other.fraction &&
          tip == other.tip &&
          scannedTo == other.scannedTo &&
          blocksRemaining == other.blocksRemaining &&
          failed == other.failed;
}

/// How far the private transparent ledger has read.
///
/// The interface needs this beside the balance, not instead of it. A
/// transparent balance is true as of a height, and a wallet that has not read
/// as far as the tip is not the same as one that read the whole chain and found
/// nothing — but they show the same number.
class ApiTransparentCoverage {
  /// The last height covered by sealed shards alone.
  ///
  /// Absent when nothing has been read: no transparent service is
  /// configured, or the wallet has not scanned down to the covered range.
  /// Absent is not zero, and must not be presented as though it were.
  final int? settledThrough;

  /// The last height covered, including a shard that can still be replaced.
  final int? coveredThrough;

  /// Spends the ledger could not resolve to an output it holds.
  ///
  /// Non-zero means the balance is too high: an output is still counted that
  /// something has already consumed. The interface must not call the balance
  /// synchronized while this is set, however current the coverage looks.
  final int unresolvedSpends;

  /// How many unsealed shard revisions the coverage rests on.
  final int provisionalShards;

  /// Page retrievals the ledger still owes from a sync that stopped short.
  ///
  /// Non-zero means the coverage describes what has been read so far, and
  /// the next sync continues it.
  final int pendingPages;

  /// The height the ledger last accepted as the end of complete coverage.
  final int? anchorHeight;

  /// Why the last sync stopped: `complete`, or the reason it stopped short
  /// (`query-budget`, `byte-budget`, `pending-limit`, `overloaded:<shard>`,
  /// `chain-unknown:<height>`, `discovery-unbounded`). Absent before any
  /// sync. The interface may call the transparent balance synchronized only
  /// when this is `complete` and `unresolved_spends` is zero.
  final String? completion;

  const ApiTransparentCoverage({
    this.settledThrough,
    this.coveredThrough,
    required this.unresolvedSpends,
    required this.provisionalShards,
    required this.pendingPages,
    this.anchorHeight,
    this.completion,
  });

  @override
  int get hashCode =>
      settledThrough.hashCode ^
      coveredThrough.hashCode ^
      unresolvedSpends.hashCode ^
      provisionalShards.hashCode ^
      pendingPages.hashCode ^
      anchorHeight.hashCode ^
      completion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTransparentCoverage &&
          runtimeType == other.runtimeType &&
          settledThrough == other.settledThrough &&
          coveredThrough == other.coveredThrough &&
          unresolvedSpends == other.unresolvedSpends &&
          provisionalShards == other.provisionalShards &&
          pendingPages == other.pendingPages &&
          anchorHeight == other.anchorHeight &&
          completion == other.completion;
}

/// One transparent output the ledger holds.
class ApiTransparentUtxo {
  /// The address it pays.
  final String address;

  /// Its value in zatoshis.
  final BigInt value;

  /// The height it was mined at, where the ledger knows one.
  ///
  /// Absent for an output the ledger only ever saw spent: a recovered spend
  /// carries what it consumed but not the height that was created at.
  final int? minedHeight;

  const ApiTransparentUtxo({
    required this.address,
    required this.value,
    this.minedHeight,
  });

  @override
  int get hashCode => address.hashCode ^ value.hashCode ^ minedHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTransparentUtxo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          value == other.value &&
          minedHeight == other.minedHeight;
}
