// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// An account the wallet holds.
class ApiAccount {
  /// The wallet-local identifier.
  final int id;

  /// The height below which this account has no history.
  final int birthday;

  /// Whether the wallet can spend, or only watch.
  final bool canSpend;

  /// The ZIP 32 account index, for accounts derived from a seed.
  final int? hdAccountIndex;

  const ApiAccount({
    required this.id,
    required this.birthday,
    required this.canSpend,
    this.hdAccountIndex,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      birthday.hashCode ^
      canSpend.hashCode ^
      hdAccountIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiAccount &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          birthday == other.birthday &&
          canSpend == other.canSpend &&
          hdAccountIndex == other.hdAccountIndex;
}

/// What an account is worth, in zatoshis.
class ApiBalance {
  /// Received, unspent, and settled: what can be sent right now.
  final BigInt spendable;

  /// Received and unspent, but not yet settled.
  final BigInt pending;

  /// Committed by a transaction that has not been mined.
  final BigInt spentUnconfirmed;

  /// Value held on transparent addresses.
  ///
  /// Kept apart from `spendable` because it cannot be sent directly:
  /// transparent funds have to be shielded first.
  final BigInt transparent;

  const ApiBalance({
    required this.spendable,
    required this.pending,
    required this.spentUnconfirmed,
    required this.transparent,
  });

  @override
  int get hashCode =>
      spendable.hashCode ^
      pending.hashCode ^
      spentUnconfirmed.hashCode ^
      transparent.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBalance &&
          runtimeType == other.runtimeType &&
          spendable == other.spendable &&
          pending == other.pending &&
          spentUnconfirmed == other.spentUnconfirmed &&
          transparent == other.transparent;
}

/// Why something could not be done.
///
/// Carries the facade's stable numeric code alongside the message. The code is
/// what an application branches on; the message is for a log. Returning only a
/// message — which is what the wallet this replaces does — makes control flow
/// depend on wording, and wording changes.
class ApiError implements FrbException {
  /// The stable code. See `zakura_wallet_facade::ErrorCode`.
  final int code;

  /// What happened, for a human reading a log.
  final String message;

  const ApiError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

/// One transaction, as it affected the wallet.
class ApiHistoryEntry {
  /// The transaction's identifier, in protocol byte order.
  final Uint8List txid;

  /// The height it was mined at, or absent while it is unmined.
  final int? minedHeight;

  /// What the wallet received.
  final BigInt received;

  /// What the wallet spent.
  final BigInt spent;

  /// Whether everything received was change.
  final bool isChangeOnly;

  const ApiHistoryEntry({
    required this.txid,
    this.minedHeight,
    required this.received,
    required this.spent,
    required this.isChangeOnly,
  });

  @override
  int get hashCode =>
      txid.hashCode ^
      minedHeight.hashCode ^
      received.hashCode ^
      spent.hashCode ^
      isChangeOnly.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiHistoryEntry &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          minedHeight == other.minedHeight &&
          received == other.received &&
          spent == other.spent &&
          isChangeOnly == other.isChangeOnly;
}

/// What came back from broadcasting.
class ApiSendReceipt {
  /// The transaction's identifier.
  final Uint8List txid;

  /// What the server said. Acceptance means it reached the network, not that
  /// it will be mined.
  final String serverResponse;

  /// Set when the payment was sent but the wallet could not record it.
  ///
  /// Not a failure of the send — the money is gone either way — but the
  /// balance will not account for it until the next scan finds it.
  final String? warning;

  const ApiSendReceipt({
    required this.txid,
    required this.serverResponse,
    this.warning,
  });

  @override
  int get hashCode =>
      txid.hashCode ^ serverResponse.hashCode ^ warning.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSendReceipt &&
          runtimeType == other.runtimeType &&
          txid == other.txid &&
          serverResponse == other.serverResponse &&
          warning == other.warning;
}

/// What a payment would cost.
class ApiSpendQuote {
  /// What the recipient receives.
  final BigInt amount;

  /// The fee.
  final BigInt fee;

  /// What comes back to the wallet.
  final BigInt change;

  /// How many notes would be spent, and so how many proofs.
  final int inputs;

  /// Whether this payment leaves the Orchard pool as a ZIP 318 crossing.
  ///
  /// A crossing pays a fixed denomination for a fixed fee, so its numbers are
  /// not negotiable the way an ordinary payment's are.
  final bool crossing;

  const ApiSpendQuote({
    required this.amount,
    required this.fee,
    required this.change,
    required this.inputs,
    required this.crossing,
  });

  @override
  int get hashCode =>
      amount.hashCode ^
      fee.hashCode ^
      change.hashCode ^
      inputs.hashCode ^
      crossing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSpendQuote &&
          runtimeType == other.runtimeType &&
          amount == other.amount &&
          fee == other.fee &&
          change == other.change &&
          inputs == other.inputs &&
          crossing == other.crossing;
}

/// What the engine is doing.
enum ApiSyncPhase {
  /// Nothing has been scanned yet.
  bootstrapping,

  /// Working backwards through history.
  recovering,

  /// Following the chain tip.
  tracking,

  /// Nothing left to scan right now — which is not the same as finished.
  idle,

  /// Not running.
  stopped,
}

/// How far synchronisation has got.
class ApiSyncProgress {
  /// What the engine is doing.
  final ApiSyncPhase phase;

  /// Commitment coverage between 0 and 1, if there is anything to measure.
  final double? fraction;

  /// The highest block the server reported.
  final int? tip;

  /// The highest block the wallet has scanned.
  final int? scannedTo;

  /// How many blocks remain queued.
  final BigInt blocksRemaining;

  /// Whether the last attempt ended in a failure rather than a finish.
  ///
  /// An unreachable server leaves the engine stopped with nothing queued,
  /// which is what having caught up looks like too. Without this an interface
  /// cannot tell them apart, and would say a wallet is up to date when it has
  /// not spoken to a server.
  final bool failed;

  const ApiSyncProgress({
    required this.phase,
    this.fraction,
    this.tip,
    this.scannedTo,
    required this.blocksRemaining,
    required this.failed,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      fraction.hashCode ^
      tip.hashCode ^
      scannedTo.hashCode ^
      blocksRemaining.hashCode ^
      failed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiSyncProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          fraction == other.fraction &&
          tip == other.tip &&
          scannedTo == other.scannedTo &&
          blocksRemaining == other.blocksRemaining &&
          failed == other.failed;
}
