// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/types.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wallet`

/// Generates a new seed phrase.
///
/// The phrase is the wallet. Whatever receives it is responsible for showing it
/// once and then storing it where the operating system protects it — this
/// library does not store it, by design.
Future<String> generateMnemonic() =>
    RustLib.instance.api.crateApiGenerateMnemonic();

/// Returns whether a phrase is a valid mnemonic.
Future<bool> validateMnemonic({required String phrase}) =>
    RustLib.instance.api.crateApiValidateMnemonic(phrase: phrase);

/// Opens or creates the wallet in `directory`.
///
/// Replaces any wallet already open, stopping its sync first.
Future<void> open({
  required String directory,
  required String lightwalletdUrl,
  required bool mainnet,
}) => RustLib.instance.api.crateApiOpen(
  directory: directory,
  lightwalletdUrl: lightwalletdUrl,
  mainnet: mainnet,
);

/// Creates a new wallet from a seed phrase, and returns its account.
///
/// For a wallet that has never existed before. Its birthday is the current
/// chain tip, because an account created now cannot have been paid earlier —
/// so there is nothing below the tip worth scanning. If the server cannot be
/// reached the earliest possible height is used instead: slower, and never
/// wrong in the direction that loses money.
///
/// The seed is derived, used and dropped. Only the viewing key is stored, so
/// the ability to spend never sits in the same file as the ability to see —
/// which is also why the phrase has to be supplied again to send.
Future<int> createAccount({required String phrase, int? birthday}) => RustLib
    .instance
    .api
    .crateApiCreateAccount(phrase: phrase, birthday: birthday);

/// Restores an existing wallet from its seed phrase.
///
/// `birthday` is the height below which the wallet is known to have no history.
/// Leaving it unset means "not known", and scans from [`earliest_birthday`]
/// rather than guessing: a guess that is too high skips the blocks the money
/// arrived in, and the wallet then shows a balance that is simply missing
/// funds, with nothing to say so.
///
/// Fails with the `AccountExists` code if this wallet is already here. Two
/// accounts sharing a viewing key would see the same notes and double every
/// balance.
Future<int> importAccount({required String phrase, int? birthday}) => RustLib
    .instance
    .api
    .crateApiImportAccount(phrase: phrase, birthday: birthday);

/// Imports a watch-only account from a unified full viewing key.
///
/// It can see everything and sign nothing. Sending from it is refused with the
/// `WatchOnly` code.
Future<int> importViewingKey({required String key, int? birthday}) =>
    RustLib.instance.api.crateApiImportViewingKey(key: key, birthday: birthday);

/// Returns the earliest height an account on this network could have history
/// at.
///
/// What an unknown birthday falls back to, and what to offer somebody who does
/// not know theirs.
Future<int> earliestBirthday() =>
    RustLib.instance.api.crateApiEarliestBirthday();

/// Asks the server for the current chain tip.
///
/// Useful for showing somebody restoring what the range of sensible birthdays
/// is.
Future<int> chainTip() => RustLib.instance.api.crateApiChainTip();

/// Returns every account, in creation order.
Future<List<ApiAccount>> accounts() => RustLib.instance.api.crateApiAccounts();

/// Returns an account's balance across every shielded pool.
///
/// Transparent value is not included: this build cannot spend it, and a balance
/// the wallet cannot back is worse than no balance.
Future<ApiBalance> balance({required int account}) =>
    RustLib.instance.api.crateApiBalance(account: account);

/// Returns how far the private transparent ledger has read for an account.
///
/// Transparent funds are discovered by that ledger and by nothing else, so
/// this is what lets the interface say "current through block N" rather than
/// implying the transparent balance is live. See
/// `docs/zakura_transparent_pir.md`.
Future<ApiTransparentCoverage> transparentCoverage({required int account}) =>
    RustLib.instance.api.crateApiTransparentCoverage(account: account);

/// Returns the transparent addresses the wallet watches for an account.
///
/// A diagnostic. An address missing here is one the gap limit did not reach,
/// and a payment to it is one the ledger will never be asked about.
Future<List<String>> transparentAddresses({required int account}) =>
    RustLib.instance.api.crateApiTransparentAddresses(account: account);

/// Returns every unspent transparent output the ledger holds for an account.
///
/// Everything it holds, not only what can be spent: filtering by maturity would
/// answer "nothing" for a wallet that holds funds it cannot spend yet, which is
/// the confusion this exists to remove.
Future<List<ApiTransparentUtxo>> transparentUtxos({required int account}) =>
    RustLib.instance.api.crateApiTransparentUtxos(account: account);

/// Returns an account's transactions, most recent first.
Future<List<ApiHistoryEntry>> history({
  required int account,
  required int limit,
}) => RustLib.instance.api.crateApiHistory(account: account, limit: limit);

/// Issues the next unused receive address.
///
/// Two calls return two different addresses: reusing one lets anybody who has
/// seen it link the payments made to it.
Future<String> nextAddress({required int account}) =>
    RustLib.instance.api.crateApiNextAddress(account: account);

/// Starts synchronising, returning immediately.
Future<void> startSync() => RustLib.instance.api.crateApiStartSync();

/// Stops synchronising, waiting for the batch in flight to finish.
Future<void> stopSync() => RustLib.instance.api.crateApiStopSync();

/// Returns how far synchronisation has got.
///
/// A poll rather than a stream. The engine publishes progress on a lossy
/// channel by design, so a reader that falls behind should see the latest value
/// rather than a queue of stale ones, and a poll expresses that directly
/// instead of marshalling a callback back into another language's runtime.
Future<ApiSyncProgress> progress() => RustLib.instance.api.crateApiProgress();

/// Returns why the last sync stopped, if it stopped because of a failure.
///
/// Cleared when a new sync starts. The message is for a log or a details pane;
/// `ApiSyncProgress::failed` is what an interface branches on.
Future<String?> syncFailure() => RustLib.instance.api.crateApiSyncFailure();

/// Works out what a payment would cost, without proving it.
Future<ApiSpendQuote> quote({
  required int account,
  required String to,
  required BigInt amount,
}) => RustLib.instance.api.crateApiQuote(
  account: account,
  to: to,
  amount: amount,
);

/// Builds, proves, signs and broadcasts a payment.
///
/// Takes seconds. The code generator runs this on a worker rather than on the
/// interface thread, but whatever calls it should already be saying that
/// something is happening.
Future<ApiSendReceipt> send({
  required int account,
  required String to,
  required BigInt amount,
  required String phrase,
}) => RustLib.instance.api.crateApiSend(
  account: account,
  to: to,
  amount: amount,
  phrase: phrase,
);

/// Closes the wallet, stopping any sync.
Future<void> close() => RustLib.instance.api.crateApiClose();
