// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 912032790;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'zakura_wallet_bridge',
        ioDirectory: '../bridge/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<ApiAccount>> crateApiAccounts();

  Future<ApiBalance> crateApiBalance({required int account});

  Future<ApiBuildInfo> crateApiBuildInfo();

  Future<int> crateApiChainTip();

  Future<void> crateApiClose();

  Future<int> crateApiCreateAccount({required String phrase, int? birthday});

  Future<int> crateApiEarliestBirthday();

  Future<String> crateApiGenerateMnemonic();

  Future<List<ApiHistoryEntry>> crateApiHistory({
    required int account,
    required int limit,
  });

  Future<int> crateApiImportAccount({required String phrase, int? birthday});

  Future<int> crateApiImportViewingKey({required String key, int? birthday});

  Future<int> crateApiLiveHeight({required String lightwalletdUrl});

  Future<ApiNetworkIdentity> crateApiNetworkIdentity({
    required String lightwalletdUrl,
  });

  Future<String> crateApiNextAddress({required int account});

  Future<void> crateApiOpen({
    required String directory,
    required String lightwalletdUrl,
    required bool mainnet,
    String? transparentFiltersUrl,
    String? transparentShardsUrl,
  });

  Future<ApiSyncProgress> crateApiProgress();

  Future<ApiSpendQuote> crateApiQuote({
    required int account,
    required String to,
    required BigInt amount,
  });

  Future<void> crateApiReset();

  Future<ApiSendReceipt> crateApiSend({
    required int account,
    required String to,
    required BigInt amount,
    required String phrase,
  });

  Future<void> crateApiStartSync();

  Future<void> crateApiStopSync();

  Future<String?> crateApiSyncFailure();

  Future<List<String>> crateApiTransparentAddresses({required int account});

  Future<ApiTransparentCoverage> crateApiTransparentCoverage({
    required int account,
  });

  Future<List<ApiTransparentUtxo>> crateApiTransparentUtxos({
    required int account,
  });

  Future<bool> crateApiValidateMnemonic({required String phrase});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<ApiAccount>> crateApiAccounts() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_account,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiAccountsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAccountsConstMeta =>
      const TaskConstMeta(debugName: "accounts", argNames: []);

  @override
  Future<ApiBalance> crateApiBalance({required int account}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_balance,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiBalanceConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBalanceConstMeta =>
      const TaskConstMeta(debugName: "balance", argNames: ["account"]);

  @override
  Future<ApiBuildInfo> crateApiBuildInfo() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_build_info,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBuildInfoConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBuildInfoConstMeta =>
      const TaskConstMeta(debugName: "build_info", argNames: []);

  @override
  Future<int> crateApiChainTip() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiChainTipConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiChainTipConstMeta =>
      const TaskConstMeta(debugName: "chain_tip", argNames: []);

  @override
  Future<void> crateApiClose() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiCloseConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCloseConstMeta =>
      const TaskConstMeta(debugName: "close", argNames: []);

  @override
  Future<int> crateApiCreateAccount({required String phrase, int? birthday}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          sse_encode_opt_box_autoadd_u_32(birthday, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiCreateAccountConstMeta,
        argValues: [phrase, birthday],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateAccountConstMeta => const TaskConstMeta(
    debugName: "create_account",
    argNames: ["phrase", "birthday"],
  );

  @override
  Future<int> crateApiEarliestBirthday() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiEarliestBirthdayConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEarliestBirthdayConstMeta =>
      const TaskConstMeta(debugName: "earliest_birthday", argNames: []);

  @override
  Future<String> crateApiGenerateMnemonic() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGenerateMnemonicConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGenerateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "generate_mnemonic", argNames: []);

  @override
  Future<List<ApiHistoryEntry>> crateApiHistory({
    required int account,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_history_entry,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiHistoryConstMeta,
        argValues: [account, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHistoryConstMeta =>
      const TaskConstMeta(debugName: "history", argNames: ["account", "limit"]);

  @override
  Future<int> crateApiImportAccount({required String phrase, int? birthday}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          sse_encode_opt_box_autoadd_u_32(birthday, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiImportAccountConstMeta,
        argValues: [phrase, birthday],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportAccountConstMeta => const TaskConstMeta(
    debugName: "import_account",
    argNames: ["phrase", "birthday"],
  );

  @override
  Future<int> crateApiImportViewingKey({required String key, int? birthday}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(key, serializer);
          sse_encode_opt_box_autoadd_u_32(birthday, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiImportViewingKeyConstMeta,
        argValues: [key, birthday],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiImportViewingKeyConstMeta => const TaskConstMeta(
    debugName: "import_viewing_key",
    argNames: ["key", "birthday"],
  );

  @override
  Future<int> crateApiLiveHeight({required String lightwalletdUrl}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lightwalletdUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiLiveHeightConstMeta,
        argValues: [lightwalletdUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLiveHeightConstMeta => const TaskConstMeta(
    debugName: "live_height",
    argNames: ["lightwalletdUrl"],
  );

  @override
  Future<ApiNetworkIdentity> crateApiNetworkIdentity({
    required String lightwalletdUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(lightwalletdUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_network_identity,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiNetworkIdentityConstMeta,
        argValues: [lightwalletdUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNetworkIdentityConstMeta => const TaskConstMeta(
    debugName: "network_identity",
    argNames: ["lightwalletdUrl"],
  );

  @override
  Future<String> crateApiNextAddress({required int account}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiNextAddressConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiNextAddressConstMeta =>
      const TaskConstMeta(debugName: "next_address", argNames: ["account"]);

  @override
  Future<void> crateApiOpen({
    required String directory,
    required String lightwalletdUrl,
    required bool mainnet,
    String? transparentFiltersUrl,
    String? transparentShardsUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(directory, serializer);
          sse_encode_String(lightwalletdUrl, serializer);
          sse_encode_bool(mainnet, serializer);
          sse_encode_opt_String(transparentFiltersUrl, serializer);
          sse_encode_opt_String(transparentShardsUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiOpenConstMeta,
        argValues: [
          directory,
          lightwalletdUrl,
          mainnet,
          transparentFiltersUrl,
          transparentShardsUrl,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiOpenConstMeta => const TaskConstMeta(
    debugName: "open",
    argNames: [
      "directory",
      "lightwalletdUrl",
      "mainnet",
      "transparentFiltersUrl",
      "transparentShardsUrl",
    ],
  );

  @override
  Future<ApiSyncProgress> crateApiProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_sync_progress,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProgressConstMeta =>
      const TaskConstMeta(debugName: "progress", argNames: []);

  @override
  Future<ApiSpendQuote> crateApiQuote({
    required int account,
    required String to,
    required BigInt amount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          sse_encode_String(to, serializer);
          sse_encode_u_64(amount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_spend_quote,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiQuoteConstMeta,
        argValues: [account, to, amount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiQuoteConstMeta => const TaskConstMeta(
    debugName: "quote",
    argNames: ["account", "to", "amount"],
  );

  @override
  Future<void> crateApiReset() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiResetConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiResetConstMeta =>
      const TaskConstMeta(debugName: "reset", argNames: []);

  @override
  Future<ApiSendReceipt> crateApiSend({
    required int account,
    required String to,
    required BigInt amount,
    required String phrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          sse_encode_String(to, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_send_receipt,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiSendConstMeta,
        argValues: [account, to, amount, phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendConstMeta => const TaskConstMeta(
    debugName: "send",
    argNames: ["account", "to", "amount", "phrase"],
  );

  @override
  Future<void> crateApiStartSync() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiStartSyncConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStartSyncConstMeta =>
      const TaskConstMeta(debugName: "start_sync", argNames: []);

  @override
  Future<void> crateApiStopSync() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiStopSyncConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopSyncConstMeta =>
      const TaskConstMeta(debugName: "stop_sync", argNames: []);

  @override
  Future<String?> crateApiSyncFailure() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiSyncFailureConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncFailureConstMeta =>
      const TaskConstMeta(debugName: "sync_failure", argNames: []);

  @override
  Future<List<String>> crateApiTransparentAddresses({required int account}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransparentAddressesConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransparentAddressesConstMeta =>
      const TaskConstMeta(
        debugName: "transparent_addresses",
        argNames: ["account"],
      );

  @override
  Future<ApiTransparentCoverage> crateApiTransparentCoverage({
    required int account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_api_transparent_coverage,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransparentCoverageConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransparentCoverageConstMeta =>
      const TaskConstMeta(
        debugName: "transparent_coverage",
        argNames: ["account"],
      );

  @override
  Future<List<ApiTransparentUtxo>> crateApiTransparentUtxos({
    required int account,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_api_transparent_utxo,
          decodeErrorData: sse_decode_api_error,
        ),
        constMeta: kCrateApiTransparentUtxosConstMeta,
        argValues: [account],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTransparentUtxosConstMeta => const TaskConstMeta(
    debugName: "transparent_utxos",
    argNames: ["account"],
  );

  @override
  Future<bool> crateApiValidateMnemonic({required String phrase}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(phrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 26,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiValidateMnemonicConstMeta,
        argValues: [phrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiValidateMnemonicConstMeta =>
      const TaskConstMeta(debugName: "validate_mnemonic", argNames: ["phrase"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ApiAccount dco_decode_api_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ApiAccount(
      id: dco_decode_u_32(arr[0]),
      birthday: dco_decode_u_32(arr[1]),
      canSpend: dco_decode_bool(arr[2]),
      hdAccountIndex: dco_decode_opt_box_autoadd_u_32(arr[3]),
    );
  }

  @protected
  ApiBalance dco_decode_api_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiBalance(
      spendable: dco_decode_u_64(arr[0]),
      pending: dco_decode_u_64(arr[1]),
      spentUnconfirmed: dco_decode_u_64(arr[2]),
      transparent: dco_decode_u_64(arr[3]),
      coverage: dco_decode_api_transparent_coverage(arr[4]),
    );
  }

  @protected
  ApiBuildInfo dco_decode_api_build_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiBuildInfo(
      sendEnabled: dco_decode_bool(arr[0]),
      transparentSchema: dco_decode_String(arr[1]),
      layoutVersion: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  ApiError dco_decode_api_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ApiError(
      code: dco_decode_u_32(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  ApiHistoryEntry dco_decode_api_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ApiHistoryEntry(
      txid: dco_decode_list_prim_u_8_strict(arr[0]),
      minedHeight: dco_decode_opt_box_autoadd_u_32(arr[1]),
      received: dco_decode_u_64(arr[2]),
      spent: dco_decode_u_64(arr[3]),
      isChangeOnly: dco_decode_bool(arr[4]),
      receivedByPool: dco_decode_api_pool_amounts(arr[5]),
      spentByPool: dco_decode_api_pool_amounts(arr[6]),
      paidToTransparent: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  ApiNetworkIdentity dco_decode_api_network_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApiNetworkIdentity(
      chainName: dco_decode_String(arr[0]),
      saplingActivationHeight: dco_decode_u_64(arr[1]),
      consensusBranchId: dco_decode_String(arr[2]),
      blockHeight: dco_decode_u_64(arr[3]),
      vendor: dco_decode_String(arr[4]),
      version: dco_decode_String(arr[5]),
    );
  }

  @protected
  ApiPoolAmounts dco_decode_api_pool_amounts(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiPoolAmounts(
      orchard: dco_decode_u_64(arr[0]),
      ironwood: dco_decode_u_64(arr[1]),
      transparent: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  ApiSendReceipt dco_decode_api_send_receipt(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiSendReceipt(
      txid: dco_decode_list_prim_u_8_strict(arr[0]),
      serverResponse: dco_decode_String(arr[1]),
      warning: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  ApiSpendQuote dco_decode_api_spend_quote(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ApiSpendQuote(
      amount: dco_decode_u_64(arr[0]),
      fee: dco_decode_u_64(arr[1]),
      change: dco_decode_u_64(arr[2]),
      inputs: dco_decode_u_32(arr[3]),
      crossing: dco_decode_bool(arr[4]),
    );
  }

  @protected
  ApiSyncPhase dco_decode_api_sync_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ApiSyncPhase.values[raw as int];
  }

  @protected
  ApiSyncProgress dco_decode_api_sync_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ApiSyncProgress(
      phase: dco_decode_api_sync_phase(arr[0]),
      fraction: dco_decode_opt_box_autoadd_f_64(arr[1]),
      tip: dco_decode_opt_box_autoadd_u_32(arr[2]),
      scannedTo: dco_decode_opt_box_autoadd_u_32(arr[3]),
      blocksRemaining: dco_decode_u_64(arr[4]),
      failed: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ApiTransparentCoverage dco_decode_api_transparent_coverage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ApiTransparentCoverage(
      settledThrough: dco_decode_opt_box_autoadd_u_32(arr[0]),
      coveredThrough: dco_decode_opt_box_autoadd_u_32(arr[1]),
      unresolvedSpends: dco_decode_u_32(arr[2]),
      provisionalShards: dco_decode_u_32(arr[3]),
      pendingPages: dco_decode_u_32(arr[4]),
      anchorHeight: dco_decode_opt_box_autoadd_u_32(arr[5]),
      completion: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  ApiTransparentUtxo dco_decode_api_transparent_utxo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ApiTransparentUtxo(
      address: dco_decode_String(arr[0]),
      value: dco_decode_u_64(arr[1]),
      minedHeight: dco_decode_opt_box_autoadd_u_32(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ApiAccount> dco_decode_list_api_account(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_account).toList();
  }

  @protected
  List<ApiHistoryEntry> dco_decode_list_api_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_history_entry).toList();
  }

  @protected
  List<ApiTransparentUtxo> dco_decode_list_api_transparent_utxo(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_api_transparent_utxo).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ApiAccount sse_decode_api_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_u_32(deserializer);
    var var_birthday = sse_decode_u_32(deserializer);
    var var_canSpend = sse_decode_bool(deserializer);
    var var_hdAccountIndex = sse_decode_opt_box_autoadd_u_32(deserializer);
    return ApiAccount(
      id: var_id,
      birthday: var_birthday,
      canSpend: var_canSpend,
      hdAccountIndex: var_hdAccountIndex,
    );
  }

  @protected
  ApiBalance sse_decode_api_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spendable = sse_decode_u_64(deserializer);
    var var_pending = sse_decode_u_64(deserializer);
    var var_spentUnconfirmed = sse_decode_u_64(deserializer);
    var var_transparent = sse_decode_u_64(deserializer);
    var var_coverage = sse_decode_api_transparent_coverage(deserializer);
    return ApiBalance(
      spendable: var_spendable,
      pending: var_pending,
      spentUnconfirmed: var_spentUnconfirmed,
      transparent: var_transparent,
      coverage: var_coverage,
    );
  }

  @protected
  ApiBuildInfo sse_decode_api_build_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sendEnabled = sse_decode_bool(deserializer);
    var var_transparentSchema = sse_decode_String(deserializer);
    var var_layoutVersion = sse_decode_u_32(deserializer);
    return ApiBuildInfo(
      sendEnabled: var_sendEnabled,
      transparentSchema: var_transparentSchema,
      layoutVersion: var_layoutVersion,
    );
  }

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ApiError(code: var_code, message: var_message);
  }

  @protected
  ApiHistoryEntry sse_decode_api_history_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_list_prim_u_8_strict(deserializer);
    var var_minedHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_received = sse_decode_u_64(deserializer);
    var var_spent = sse_decode_u_64(deserializer);
    var var_isChangeOnly = sse_decode_bool(deserializer);
    var var_receivedByPool = sse_decode_api_pool_amounts(deserializer);
    var var_spentByPool = sse_decode_api_pool_amounts(deserializer);
    var var_paidToTransparent = sse_decode_u_64(deserializer);
    return ApiHistoryEntry(
      txid: var_txid,
      minedHeight: var_minedHeight,
      received: var_received,
      spent: var_spent,
      isChangeOnly: var_isChangeOnly,
      receivedByPool: var_receivedByPool,
      spentByPool: var_spentByPool,
      paidToTransparent: var_paidToTransparent,
    );
  }

  @protected
  ApiNetworkIdentity sse_decode_api_network_identity(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_chainName = sse_decode_String(deserializer);
    var var_saplingActivationHeight = sse_decode_u_64(deserializer);
    var var_consensusBranchId = sse_decode_String(deserializer);
    var var_blockHeight = sse_decode_u_64(deserializer);
    var var_vendor = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    return ApiNetworkIdentity(
      chainName: var_chainName,
      saplingActivationHeight: var_saplingActivationHeight,
      consensusBranchId: var_consensusBranchId,
      blockHeight: var_blockHeight,
      vendor: var_vendor,
      version: var_version,
    );
  }

  @protected
  ApiPoolAmounts sse_decode_api_pool_amounts(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_orchard = sse_decode_u_64(deserializer);
    var var_ironwood = sse_decode_u_64(deserializer);
    var var_transparent = sse_decode_u_64(deserializer);
    return ApiPoolAmounts(
      orchard: var_orchard,
      ironwood: var_ironwood,
      transparent: var_transparent,
    );
  }

  @protected
  ApiSendReceipt sse_decode_api_send_receipt(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txid = sse_decode_list_prim_u_8_strict(deserializer);
    var var_serverResponse = sse_decode_String(deserializer);
    var var_warning = sse_decode_opt_String(deserializer);
    return ApiSendReceipt(
      txid: var_txid,
      serverResponse: var_serverResponse,
      warning: var_warning,
    );
  }

  @protected
  ApiSpendQuote sse_decode_api_spend_quote(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_amount = sse_decode_u_64(deserializer);
    var var_fee = sse_decode_u_64(deserializer);
    var var_change = sse_decode_u_64(deserializer);
    var var_inputs = sse_decode_u_32(deserializer);
    var var_crossing = sse_decode_bool(deserializer);
    return ApiSpendQuote(
      amount: var_amount,
      fee: var_fee,
      change: var_change,
      inputs: var_inputs,
      crossing: var_crossing,
    );
  }

  @protected
  ApiSyncPhase sse_decode_api_sync_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ApiSyncPhase.values[inner];
  }

  @protected
  ApiSyncProgress sse_decode_api_sync_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_api_sync_phase(deserializer);
    var var_fraction = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_tip = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_scannedTo = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_blocksRemaining = sse_decode_u_64(deserializer);
    var var_failed = sse_decode_bool(deserializer);
    return ApiSyncProgress(
      phase: var_phase,
      fraction: var_fraction,
      tip: var_tip,
      scannedTo: var_scannedTo,
      blocksRemaining: var_blocksRemaining,
      failed: var_failed,
    );
  }

  @protected
  ApiTransparentCoverage sse_decode_api_transparent_coverage(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_settledThrough = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_coveredThrough = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_unresolvedSpends = sse_decode_u_32(deserializer);
    var var_provisionalShards = sse_decode_u_32(deserializer);
    var var_pendingPages = sse_decode_u_32(deserializer);
    var var_anchorHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_completion = sse_decode_opt_String(deserializer);
    return ApiTransparentCoverage(
      settledThrough: var_settledThrough,
      coveredThrough: var_coveredThrough,
      unresolvedSpends: var_unresolvedSpends,
      provisionalShards: var_provisionalShards,
      pendingPages: var_pendingPages,
      anchorHeight: var_anchorHeight,
      completion: var_completion,
    );
  }

  @protected
  ApiTransparentUtxo sse_decode_api_transparent_utxo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_value = sse_decode_u_64(deserializer);
    var var_minedHeight = sse_decode_opt_box_autoadd_u_32(deserializer);
    return ApiTransparentUtxo(
      address: var_address,
      value: var_value,
      minedHeight: var_minedHeight,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiAccount> sse_decode_list_api_account(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiAccount>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_account(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiHistoryEntry> sse_decode_list_api_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<ApiTransparentUtxo> sse_decode_list_api_transparent_utxo(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ApiTransparentUtxo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_api_transparent_utxo(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_api_account(ApiAccount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.id, serializer);
    sse_encode_u_32(self.birthday, serializer);
    sse_encode_bool(self.canSpend, serializer);
    sse_encode_opt_box_autoadd_u_32(self.hdAccountIndex, serializer);
  }

  @protected
  void sse_encode_api_balance(ApiBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.spendable, serializer);
    sse_encode_u_64(self.pending, serializer);
    sse_encode_u_64(self.spentUnconfirmed, serializer);
    sse_encode_u_64(self.transparent, serializer);
    sse_encode_api_transparent_coverage(self.coverage, serializer);
  }

  @protected
  void sse_encode_api_build_info(ApiBuildInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.sendEnabled, serializer);
    sse_encode_String(self.transparentSchema, serializer);
    sse_encode_u_32(self.layoutVersion, serializer);
  }

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_api_history_entry(
    ApiHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.txid, serializer);
    sse_encode_opt_box_autoadd_u_32(self.minedHeight, serializer);
    sse_encode_u_64(self.received, serializer);
    sse_encode_u_64(self.spent, serializer);
    sse_encode_bool(self.isChangeOnly, serializer);
    sse_encode_api_pool_amounts(self.receivedByPool, serializer);
    sse_encode_api_pool_amounts(self.spentByPool, serializer);
    sse_encode_u_64(self.paidToTransparent, serializer);
  }

  @protected
  void sse_encode_api_network_identity(
    ApiNetworkIdentity self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.chainName, serializer);
    sse_encode_u_64(self.saplingActivationHeight, serializer);
    sse_encode_String(self.consensusBranchId, serializer);
    sse_encode_u_64(self.blockHeight, serializer);
    sse_encode_String(self.vendor, serializer);
    sse_encode_String(self.version, serializer);
  }

  @protected
  void sse_encode_api_pool_amounts(
    ApiPoolAmounts self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.orchard, serializer);
    sse_encode_u_64(self.ironwood, serializer);
    sse_encode_u_64(self.transparent, serializer);
  }

  @protected
  void sse_encode_api_send_receipt(
    ApiSendReceipt self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.txid, serializer);
    sse_encode_String(self.serverResponse, serializer);
    sse_encode_opt_String(self.warning, serializer);
  }

  @protected
  void sse_encode_api_spend_quote(
    ApiSpendQuote self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.amount, serializer);
    sse_encode_u_64(self.fee, serializer);
    sse_encode_u_64(self.change, serializer);
    sse_encode_u_32(self.inputs, serializer);
    sse_encode_bool(self.crossing, serializer);
  }

  @protected
  void sse_encode_api_sync_phase(ApiSyncPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_api_sync_progress(
    ApiSyncProgress self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_api_sync_phase(self.phase, serializer);
    sse_encode_opt_box_autoadd_f_64(self.fraction, serializer);
    sse_encode_opt_box_autoadd_u_32(self.tip, serializer);
    sse_encode_opt_box_autoadd_u_32(self.scannedTo, serializer);
    sse_encode_u_64(self.blocksRemaining, serializer);
    sse_encode_bool(self.failed, serializer);
  }

  @protected
  void sse_encode_api_transparent_coverage(
    ApiTransparentCoverage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_u_32(self.settledThrough, serializer);
    sse_encode_opt_box_autoadd_u_32(self.coveredThrough, serializer);
    sse_encode_u_32(self.unresolvedSpends, serializer);
    sse_encode_u_32(self.provisionalShards, serializer);
    sse_encode_u_32(self.pendingPages, serializer);
    sse_encode_opt_box_autoadd_u_32(self.anchorHeight, serializer);
    sse_encode_opt_String(self.completion, serializer);
  }

  @protected
  void sse_encode_api_transparent_utxo(
    ApiTransparentUtxo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_u_64(self.value, serializer);
    sse_encode_opt_box_autoadd_u_32(self.minedHeight, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_account(
    List<ApiAccount> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_account(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_history_entry(
    List<ApiHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_api_transparent_utxo(
    List<ApiTransparentUtxo> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_api_transparent_utxo(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
