// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'api/types.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiAccount dco_decode_api_account(dynamic raw);

  @protected
  ApiBalance dco_decode_api_balance(dynamic raw);

  @protected
  ApiError dco_decode_api_error(dynamic raw);

  @protected
  ApiHistoryEntry dco_decode_api_history_entry(dynamic raw);

  @protected
  ApiPoolAmounts dco_decode_api_pool_amounts(dynamic raw);

  @protected
  ApiSendReceipt dco_decode_api_send_receipt(dynamic raw);

  @protected
  ApiSpendQuote dco_decode_api_spend_quote(dynamic raw);

  @protected
  ApiSyncPhase dco_decode_api_sync_phase(dynamic raw);

  @protected
  ApiSyncProgress dco_decode_api_sync_progress(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<ApiAccount> dco_decode_list_api_account(dynamic raw);

  @protected
  List<ApiHistoryEntry> dco_decode_list_api_history_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiAccount sse_decode_api_account(SseDeserializer deserializer);

  @protected
  ApiBalance sse_decode_api_balance(SseDeserializer deserializer);

  @protected
  ApiError sse_decode_api_error(SseDeserializer deserializer);

  @protected
  ApiHistoryEntry sse_decode_api_history_entry(SseDeserializer deserializer);

  @protected
  ApiPoolAmounts sse_decode_api_pool_amounts(SseDeserializer deserializer);

  @protected
  ApiSendReceipt sse_decode_api_send_receipt(SseDeserializer deserializer);

  @protected
  ApiSpendQuote sse_decode_api_spend_quote(SseDeserializer deserializer);

  @protected
  ApiSyncPhase sse_decode_api_sync_phase(SseDeserializer deserializer);

  @protected
  ApiSyncProgress sse_decode_api_sync_progress(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<ApiAccount> sse_decode_list_api_account(SseDeserializer deserializer);

  @protected
  List<ApiHistoryEntry> sse_decode_list_api_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_account(ApiAccount self, SseSerializer serializer);

  @protected
  void sse_encode_api_balance(ApiBalance self, SseSerializer serializer);

  @protected
  void sse_encode_api_error(ApiError self, SseSerializer serializer);

  @protected
  void sse_encode_api_history_entry(
    ApiHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_pool_amounts(
    ApiPoolAmounts self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_send_receipt(
    ApiSendReceipt self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_api_spend_quote(ApiSpendQuote self, SseSerializer serializer);

  @protected
  void sse_encode_api_sync_phase(ApiSyncPhase self, SseSerializer serializer);

  @protected
  void sse_encode_api_sync_progress(
    ApiSyncProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_api_account(
    List<ApiAccount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_api_history_entry(
    List<ApiHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
